### ISSUE TITLE
Make the good xpath at this page 

### ISSUE THREAD

**Issue by nhungredweb** [Samgithub1997/TwitterAutomation#3]
https://github.com/Samgithub1997/TwitterAutomation/blob/2348ed86ef92c1d158ee13566f399cb1a80ccf24/tests/_support/Page/searchLike.php#L15

**Comment by Samgithub1997** [comment]
issue resolved : 
public static $searchButton = ['xpath' => '//button[@class=\'Icon Icon--medium Icon--search nav-search\']'];
